// Every string on the home page, in both languages. English is the source, as in the
// app. The Chinese is written for Chinese readers rather than translated line by line,
// and uses the app's own zh-Hans terms (统计, 记忆, 远程主机, 清理会话, 拷贝…) wherever
// the page names something in the app. `{x}` placeholders are filled in by the page.
export type Lang = 'en' | 'zh';

const en = {
  htmlLang: 'en',
  title: 'Wake — every coding-agent conversation, one search away',
  description:
    'Wake gathers the conversations you have with Claude Code, Codex, Cursor and many other coding agents into one window. Search all of them and pick sessions back up in your terminal. Local and read-only.',
  nav: { home: 'Home', download: 'Free download', docs: 'Docs', changelog: 'Changelog', github: 'GitHub', star: 'Star Wake on GitHub', language: 'Language' },
  hero: {
    title: 'Find any coding‑agent conversation in seconds.',
    lede:
      'Wake reads the history that Claude Code, Codex, Cursor and many other agents keep on your computer. Search all of it at once and pick sessions back up in your terminal. Read-only, and nothing leaves your machine.',
    cta: 'Free download',
    docs: 'Read the docs',
    free: 'Open source, MIT licensed',
    platforms: 'macOS 14+, Linux, Windows',
  },
  demo: {
    placeholder: 'Search every session',
    sidebarSearch: 'Search sessions',
    try: 'Try a search',
    allSessions: 'All Sessions',
    agents: 'Agents',
    projects: 'Projects',
    scope: 'Scope: all sessions',
    navigate: 'navigate',
    open: 'open',
    close: 'close',
    none: 'No session mentions “{q}”',
    messages: 'messages',
    sort: 'Date updated',
  },
  agents: {
    title: 'Reads each agent’s history right where it lives',
    lede:
      'No export and no account. Wake reads the files and databases every agent already writes, and never changes a byte.',
    missing:
      'Not supported yet: Windsurf and Trae encrypt their local data; Amp, Factory and Warp keep sessions in the cloud.',
  },
  resume: {
    title: 'Back in the terminal in one click',
    lede:
      "Open In runs the agent's own resume command in the session's project folder, in Terminal, iTerm2, Ghostty or Kooky. Sessions mirrored from another machine come back as a ready-to-paste ssh command.",
    openIn: 'Open In',
    copySsh: 'Copy SSH Command',
  },
  connect: {
    title: 'Your next agent can read what the last one did',
    lede:
      'Wake comes with a read-only MCP server and a command-line tool. Ask Codex why something was built the way it was, and it can look up the Claude Code session where you decided.',
    ask: 'Why did we put health checks in front of the rate limiter?',
    answer:
      'From a Codex session yesterday: load balancer probes carry no API key, so they all landed in the anonymous bucket and drained it within seconds. /healthz and /readyz were moved in front of the limiter, with a test that fires 500 probes in a row.',
    setup: 'Set it up',
    copy: 'Copy',
    copied: 'Copied',
    docs: 'MCP guide',
    cliDocs: 'CLI guide',
  },
  insights: {
    title: 'See how you work with your agents',
    lede: 'Insights draws your whole history as one picture: when you work, how long your streaks run, and which agents, projects and models you lean on. Every number is worked out on your machine.',
    ui: {
      insights: 'Insights',
      since: 'Since {}',
      sessions: 'Sessions',
      tokens: 'Tokens',
      prompts: 'Prompts',
      agents: 'Agents',
      projects: 'Projects',
      models: 'Models',
      activeDays: 'Active days',
      last7: 'Last 7 days',
      vsLastWeek: '{}% vs last week',
      same: 'Same as last week',
      activity: 'Activity',
      streak: '{}-day streak',
      longest: 'Longest {} days',
      busiest: 'Busiest {} ({})',
      less: 'Less',
      more: 'More',
      overTime: 'Over time',
      perWeek: 'Prompts per week by agent · {} leads this week',
      other: 'Other',
      byHour: 'By hour',
      byWeekday: 'By weekday',
      byMonth: 'By month',
      mostAround: 'Most active around {}',
      mostOn: 'Most active on {}',
      mostIn: 'Most active in {}',
      weekdays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      weekdaysLong: ['Mondays', 'Tuesdays', 'Wednesdays', 'Thursdays', 'Fridays', 'Saturdays', 'Sundays'],
      previous: 'Previous',
      next: 'Next',
      locale: 'en',
    },
  },
  more: {
    title: 'More than a search box',
    items: [
      {
        name: 'Memory',
        body: 'The notes agents keep for themselves and the instructions you give them, from Claude Code auto-memory to Codex memories, in one list you can search.',
        chips: ['CLAUDE.md', 'AGENTS.md', 'MEMORY.md', 'GEMINI.md', '.cursor/rules'],
        mono: true,
      },
      {
        name: 'Remote hosts',
        body: 'Mirror the sessions on your other machines over SSH. They sit next to the local ones with an @host badge and search the same way.',
        chips: ['@devbox', '@studio'],
        mono: true,
      },
      {
        name: 'Clean up',
        body: 'Find old or large sessions by when they were created, when they were last used and how much disk they take, check the list, and move them to the Trash.',
        chips: ['Updated over 90 days ago', 'Largest first'],
        mono: false,
      },
    ],
  },
  principles: {
    title: 'Your history stays on your machine',
    items: [
      { name: 'Read-only', body: "Wake never writes to an agent's files or databases. Deleting a session moves its file to the Trash; put it back and the session returns." },
      { name: 'Nothing phones home', body: 'The only request Wake makes is checking GitHub for a new version, and only when you click Check for Updates.' },
      { name: 'A cache, not a copy', body: "The search index can be deleted at any time and rebuilt from the agents' own files." },
      { name: 'Open source', body: 'MIT licensed, built in Rust with GPUI. Read every line on GitHub.' },
    ],
  },
  download: {
    title: 'Download Wake',
    released: 'Version {v}, released {date}.',
    version: 'Version {v}.',
    notes: 'Release notes',
    universal: 'Universal',
    mac: { name: 'macOS', req: 'macOS 14 or later, Apple silicon and Intel' },
    linux: { name: 'Linux', req: 'arm64 and x86_64, experimental' },
    windows: { name: 'Windows', req: 'x86_64, experimental' },
    gatekeeper:
      'Wake is ad-hoc signed, so macOS blocks the first launch. Allow it under System Settings → Privacy & Security, or run',
  },
  faq: {
    title: 'Questions',
    items: [
      { q: 'Is Wake free?', a: 'Yes. Wake is MIT-licensed open source, with no account, subscription or telemetry.' },
      { q: 'Does it upload my conversations anywhere?', a: 'No. Wake reads files on your computer and keeps its index next to them. Remote hosts are mirrored over your own SSH connection into a local cache.' },
      { q: 'Will it change my agents’ files?', a: "No. Wake only reads them; stars, pins and the search index live in Wake's own database. The one exception is deleting a session yourself: its file moves to the Trash, and putting it back restores it." },
      { q: 'How do agents use it?', a: 'Connect the bundled wake-mcp server to any MCP client, or let an agent run wake-cli in a shell. Both give the same answers, and both are read-only.' },
      { q: 'My agent isn’t listed.', a: 'If it keeps its history on disk unencrypted, open an issue on GitHub saying where the files are and what they look like. Most of the agents here were added that way.' },
    ],
  },
  docs: {
    label: 'Docs',
    mcp: 'MCP server',
    cli: 'Command line',
    changelog: 'Changelog',
    edit: 'Edit on GitHub',
    englishOnly: '',
    changelogEnglishOnly: '',
    tags: { new: 'New', fix: 'Fix', update: 'Update' },
  },
  footer: {
    credit: 'Made by {author}. MIT licensed, {year}.',
    releases: 'All releases',
    issues: 'Report an issue',
  },
};

export type Copy = typeof en;

const zh: Copy = {
  htmlLang: 'zh-Hans',
  title: 'Wake：和 coding agent 聊过的每一句，几秒就能翻出来',
  description:
    'Claude Code、Codex、Cursor 这些 coding agent 的对话记录，Wake 都收进一个窗口：全文搜索，能恢复的会话点一下就回到终端接着聊。只读，数据不出本机。',
  nav: { home: '首页', download: '免费下载', docs: '文档', changelog: '更新日志', github: 'GitHub', star: '在 GitHub 上给 Wake 点 Star', language: '语言' },
  hero: {
    title: '和 coding agent 聊过的每一句，\n几秒就能翻出来。',
    lede:
      'Claude Code、Codex、Cursor 这些 agent 的对话记录其实都在你电脑上，只是各存各的。Wake 把它们收进一个窗口，一个搜索框全都能搜；能恢复的会话，点一下就回到终端接着聊。全程只读，数据不出本机。',
    cta: '免费下载',
    docs: '查看文档',
    free: 'MIT 协议开源',
    platforms: 'macOS 14+、Linux、Windows',
  },
  demo: {
    placeholder: '搜索全部会话',
    sidebarSearch: '搜索会话',
    try: '搜搜看',
    allSessions: '全部会话',
    agents: 'Agent',
    projects: '项目',
    scope: '范围：全部会话',
    navigate: '切换',
    open: '打开',
    close: '关闭',
    none: '没有会话提到“{q}”',
    messages: '条消息',
    sort: '更新时间',
  },
  agents: {
    title: '直接读各家 agent 自己存的记录',
    lede: '不用导出，也不用注册账号。各家 agent 本来就会把对话存进自己的文件和数据库，Wake 直接去读，原文件一个字节都不改。',
    missing: '暂不支持：Windsurf 和 Trae 的本地数据是加密的；Amp、Factory 和 Warp 的会话只存在云端。',
  },
  resume: {
    title: '点一下，回终端接着聊',
    lede: '在「打开方式」里选 Terminal、iTerm2、Ghostty 或 Kooky，Wake 会回到会话原来的项目目录，用 agent 自己的恢复命令接着聊。远程主机上的会话，则给你一条现成的 ssh 命令，拷贝到终端就能用。',
    openIn: '打开方式',
    copySsh: '拷贝 SSH 命令',
  },
  connect: {
    title: '上一个 agent 做过什么，下一个也能查到',
    lede: 'Wake 自带一个只读的 MCP server 和一个命令行工具。你问 Codex 某段代码当初为什么这么写，它可以直接去翻你当时在 Claude Code 里讨论的那段对话。',
    ask: '健康检查为什么要放在限流器前面？',
    answer:
      '查到了昨天的一段 Codex 会话：负载均衡器的探活请求不带 API key，全都算进了匿名请求的额度，几秒就耗光了。所以当时把 /healthz 和 /readyz 挪到了限流器前面，还补了个连发 500 次探活请求的测试。',
    setup: '接入方式',
    copy: '拷贝',
    copied: '已拷贝',
    docs: 'MCP 文档',
    cliDocs: '命令行文档',
  },
  insights: {
    title: '看看你是怎么用 agent 的',
    lede: '统计页把你全部的历史记录画成一张图：什么时候在用、连续用了多少天、最常用哪些 agent、项目和模型。所有数字都在你自己的电脑上算出来。',
    ui: {
      insights: '统计',
      since: '自 {} 起',
      sessions: '会话',
      tokens: 'Token',
      prompts: '提问',
      agents: 'Agent',
      projects: '项目',
      models: '模型',
      activeDays: '活跃天数',
      last7: '最近 7 天',
      vsLastWeek: '较上周 {}%',
      same: '与上周持平',
      activity: '活动',
      streak: '连续 {} 天',
      longest: '最长 {} 天',
      busiest: '最忙 {}（{}）',
      less: '少',
      more: '多',
      overTime: '随时间变化',
      perWeek: '各 agent 每周提问数 · 本周 {} 领先',
      other: '其他',
      byHour: '按小时',
      byWeekday: '按星期',
      byMonth: '按月份',
      mostAround: '最常在 {}',
      mostOn: '最常在{}',
      mostIn: '最常在 {}',
      weekdays: ['一', '二', '三', '四', '五', '六', '日'],
      weekdaysLong: ['周一', '周二', '周三', '周四', '周五', '周六', '周日'],
      previous: '上一个',
      next: '下一个',
      locale: 'zh-CN',
    },
  },
  more: {
    title: '不只是一个搜索框',
    items: [
      {
        name: '记忆',
        body: 'agent 给自己记的笔记（比如 Claude Code 的 auto-memory、Codex 的 memories），和你写给它们的指令放在同一个列表里，可以一起搜。',
        chips: ['CLAUDE.md', 'AGENTS.md', 'MEMORY.md', 'GEMINI.md', '.cursor/rules'],
        mono: true,
      },
      {
        name: '远程主机',
        body: '通过 SSH 把其他机器上的会话同步过来，和本机的放在一起，带 @host 标记，搜起来也没区别。',
        chips: ['@devbox', '@studio'],
        mono: true,
      },
      {
        name: '清理会话',
        body: '按创建时间、最近使用时间和占用空间筛选会话，核对列表后再移到废纸篓。',
        chips: ['超过 90 天未更新', '从大到小'],
        mono: false,
      },
    ],
  },
  principles: {
    title: '你的记录，只在你的电脑上',
    items: [
      { name: '只读', body: 'Wake 不会改写 agent 的文件和数据库。删除会话只是把文件移进废纸篓，放回原处，会话就回来了。' },
      { name: '不自动联网', body: 'Wake 唯一会发出的网络请求是去 GitHub 查新版本，而且只在你点「检查更新」的时候。' },
      { name: '索引只是缓存', body: '搜索索引随时可以删，删了也能从各家 agent 的原始文件重新建出来。' },
      { name: '开源', body: 'MIT 协议，用 Rust 和 GPUI 写的，每行代码都在 GitHub 上。' },
    ],
  },
  download: {
    title: '下载 Wake',
    released: '版本 {v}，{date}发布。',
    version: '版本 {v}。',
    notes: '更新说明',
    universal: '通用版',
    mac: { name: 'macOS', req: 'macOS 14 及以上，Apple 芯片和 Intel 都支持' },
    linux: { name: 'Linux', req: 'arm64 和 x86_64，实验性支持' },
    windows: { name: 'Windows', req: 'x86_64，实验性支持' },
    gatekeeper: 'Wake 用的是 ad-hoc 签名，第一次打开会被 macOS 拦下。到「系统设置 → 隐私与安全性」里点「仍要打开」，或者在终端运行：',
  },
  faq: {
    title: '常见问题',
    items: [
      { q: 'Wake 要钱吗？', a: '不要钱。Wake 是 MIT 协议的开源软件，不用注册账号，没有订阅，也不收集使用数据。' },
      { q: '会把我的对话传到网上吗？', a: '不会。Wake 只读你电脑上的文件，索引也存在本地。远程主机的会话是通过你自己的 SSH 连接，同步到本机的缓存里。' },
      { q: '会改动 agent 自己的文件吗？', a: '不会改写。收藏、置顶和搜索索引都存在 Wake 自己的数据库里。唯一会动到原文件的是你手动删除会话：文件会移进废纸篓，放回去就恢复了。' },
      { q: 'agent 怎么用 Wake？', a: '把自带的 wake-mcp 接到任意 MCP 客户端，或者让 agent 在终端里跑 wake-cli。两种方式拿到的结果一样，也都是只读的。' },
      { q: '我用的 agent 不在列表里怎么办？', a: '只要它把历史记录存在本地，而且没有加密，就到 GitHub 提个 issue，说说文件在哪、长什么样。列表里大部分 agent 就是这么加进来的。' },
    ],
  },
  docs: {
    label: '文档',
    mcp: 'MCP server',
    cli: '命令行',
    changelog: '更新日志',
    edit: '在 GitHub 上编辑',
    englishOnly: '这份文档目前只有英文版。',
    changelogEnglishOnly: '更新日志目前只有英文版。',
    tags: { new: '新增', fix: '修复', update: '改进' },
  },
  footer: {
    credit: '{author} 开发，MIT 协议，{year}。',
    releases: '历史版本',
    issues: '反馈问题',
  },
};

export const COPY: Record<Lang, Copy> = { en, zh };

/** The same page in a given language: Chinese pages live under /zh. */
export const localePath = (lang: Lang, path: string) => (lang === 'zh' ? `/zh${path === '/' ? '/' : path}` : path);
